# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b98362154a6dace279f7a2441948c65d0ab3f3ab5bf53f702e038b08ffd688932dde8c118d521e78f224032fd93101f93578938ee1c73381e663511e8103d5f4

test:
  secret_key_base: b1084e63f89f08894571e97ffde75dbfa6f7146e8d4d24f6f42f768e89f9b292adcf1f28378e520fe8c2c7348f2b09d150f590ba5d59fd5ed83a79a39d191ef7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
